/* Automatically generated file */

#ifndef XROAR_WINDOWS_DIALOGS_H_
#define XROAR_WINDOWS_DIALOGS_H_

#define IDD_DLG_ABOUT (1)
#define IDD_DLG_TV_CONTROLS (2)
#define IDD_DLG_TAPE_CONTROLS (3)

#define IDC_EDIT_BRIGHTNESS (100)
#define IDC_SPIN_BRIGHTNESS (101)
#define IDC_EDIT_CONTRAST (102)
#define IDC_SPIN_CONTRAST (103)
#define IDC_EDIT_SATURATION (104)
#define IDC_SPIN_SATURATION (105)
#define IDC_EDIT_HUE (106)
#define IDC_SPIN_HUE (107)
#define IDC_STM_INPUT_FILENAME (108)
#define IDC_LVS_INPUT_PROGRAMLIST (109)
#define IDC_SBM_INPUT_POSITION (110)
#define IDC_STM_INPUT_POSITION (111)
#define IDC_BN_TAPE_FAST (112)
#define IDC_BN_TAPE_PAD_AUTO (113)
#define IDC_BN_TAPE_REWRITE (114)
#define IDC_BN_INPUT_PLAY (115)
#define IDC_BN_INPUT_PAUSE (116)
#define IDC_BN_INPUT_REWIND (117)
#define IDC_BN_INPUT_EJECT (118)
#define IDC_BN_INPUT_INSERT (119)
#define IDC_STM_OUTPUT_FILENAME (120)
#define IDC_SBM_OUTPUT_POSITION (121)
#define IDC_STM_OUTPUT_POSITION (122)
#define IDC_BN_OUTPUT_RECORD (123)
#define IDC_BN_OUTPUT_PAUSE (124)
#define IDC_BN_OUTPUT_REWIND (125)
#define IDC_BN_OUTPUT_EJECT (126)
#define IDC_BN_OUTPUT_INSERT (127)

#endif
